language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
